version: '3.8'

services:
  client-backend:
    image: challenge-parser:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge-parser
    ports:
      - "8181:8181"
    environment:
      - SERVER_PORT=8181
      - IKS_TELEGRAM_BOT_TOKEN=${IKS_TELEGRAM_BOT_TOKEN}
      - IKS_TELEGRAM_BOT_NAME=${IKS_TELEGRAM_BOT_NAME}
      - IKS_TELEGRAM_ADMIN_ID=${IKS_TELEGRAM_ADMIN_ID}
      - IKS_DB_USERNAME=${IKS_DB_USERNAME}
      - IKS_DB_PASSWORD=${IKS_DB_PASSWORD}
