spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

telegram:
  bot:
    token: 1223334444:55555666666677777788888888888888
    name: name_bot
    reconnectTimeout: 10000

logging:
  level:
    root: INFO
    com.dp_ua: INFO
  file: file.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
