version: '3.3'

services:
  client-backend:
    image: iks-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iks-bot
    ports:
      - "8181:8181"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT=8181
      - IKS_TELEGRAM_BOT_TOKEN=${IKS_TELEGRAM_BOT_TOKEN}
      - IKS_TELEGRAM_BOT_NAME=${IKS_TELEGRAM_BOT_NAME}
      - IKS_TELEGRAM_ADMIN_ID=${IKS_TELEGRAM_ADMIN_ID}
      - IKS_DB_USERNAME=${IKS_DB_USERNAME}
      - IKS_DB_PASSWORD=${IKS_DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8181/actuator/health" ]  # Adjust the URL based on your actual health check endpoint
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - bot-data:/var/lib/iks-bot

  service-db:
    image: postgres:14-alpine3.18
    container_name: iks-db
    environment:
      POSTGRES_USER: ${IKS_DB_USERNAME}
      POSTGRES_PASSWORD: ${IKS_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  bot-data:
  db-data:
